[ADD] website_ore : Addition Croppie
OffrirRecevoirEchanger/erplibre-addons-ore pull request #11
Opened 2023-04-20 16:15 UTC by guduyichengfeng

Ajouter la fonctionnalité de Crop les images profiles

2023-04-21 16:03 UTC, mathben commented
1. Utiliser angularjs et ng-if pour faire afficher les états au lieu de changer la visibilité manuellement
2. utiliser un dialog (comme dans participer) pour faire afficher le crop. Il peut annuler ou crop.
Tâche à continuer svp.

2023-04-25 15:39 UTC, mathben requested changes
Merci pour ta contribution, j'ai terminé ma révision. N'hésite pas si tu as des questions.

2023-04-25 15:39 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                    <i class="fa fa-pencil-square text-primary" id="submitBtn" type="submit" data-toggle="modal" data-target=".modal_pub_offre" style="padding-bottom:
pourquoi c'est un type submit? Je croyais que c'était utile pour les formulaires seulement?

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +                                console.debug("destroyed");
Enlève ça, ça semble temporaire. Sinon met un message plus explicite, les futurs développeurs ne comprendront pas pourquoi c'est écrit 'destroy' seulement dans la console.

2023-04-25 15:39 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                <!-- TODO is it used? -->
est-ce que ce todo est encore à jour?

2023-04-25 15:39 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                            <!--                                            <div>-->
ce commentaire semble deprecated?

2023-04-25 15:39 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                    <div class="profil profil_right profil_box btn btn-primary adapt-text-primary-color" ng-if="membre_info.estPersonnel &amp;&amp; ask_modification_pr
je ne trouve pas la fonction destroy

2023-04-25 15:39 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                    <div class="profil profil_left profil_box btn btn-primary adapt-text-primary-color" ng-if="membre_info.estPersonnel &amp;&amp; ask_modification_pro
je ne trouve pas la fonction destroy

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +        $scope.croppie = false;
peux-tu renommer la variable pour un état? Exemple, enable_croppie, ou show_croppie?

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +                            console.debug("close");
Même chose ici, soit que tu nettoies ce log temporaire ou que tu le rends plus explicite.

2023-04-25 15:39 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                                <button id="confirm-crop-btn" ng-click="crop_profile_picture()" data-toggle="modal" data-target=".modal_pub_offre" ng-if="croppie">Crop
le nom de la méthode devrait être en camelcase en Javascript.

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +                    // document.getElementById("confirm-crop-btn").style.visibility = "hidden";
à effacer

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +
ne pas mettre de saut de ligne vide avant la fin de la fermeture d'un statement

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +
ne pas mettre de saut de ligne vide avant la fin de la fermeture d'un statement

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +
ne pas mettre de saut de ligne vide avant la fin de la fermeture d'un statement

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +
ne pas mettre de saut de ligne vide avant la fin de la fermeture d'un statement

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +                            // modal[0].setAttribute('data-backdrop', 'static'); // add the data-backdrop attribute
est-ce que ce code est encore utile?

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +                                modal[0].classList.remove('modal_shown'); // remove the modal_shown class
peut-on mettre un commentaire de pourquoi on enlève cette classe?

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +                            $scope.show_submit_modal = false;
Tu n'utilises pas cette variable? C'est utilisé dans participer.
As-tu regardé le code dans addons/ORE_erplibre-addons-ore/website_ore/templates/website.xml ligne 1666? Il utilise ça pour afficher le modal.

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +                                modal[0].classList.remove('modal_shown'); // remove the modal_shown class
Peut-être que closeModalForm est mieux, car il devient indépendant de AngularJS, moi j'ai eu des problèmes à l'utiliser. Peux-tu m'argumenter en quoi c'est mieux svp?

2023-04-25 15:39 UTC, mathben commented on website_ore/static/src/scss/croppie/croppie.css
Puisque le fichier javascript est dans lib,
website_ore/static/src/js/lib/croppie.js
Il faudrait aussi mettre le fichier css dans lib.
website_ore/static/src/scss/lib/croppie.css

2023-04-25 15:39 UTC, mathben commented on website_ore/views/assets.xml
> +            <script type="text/javascript" src="/website_ore/static/src/js/lib/croppie.js" />
svp, met les libs avec les autres libs.

2023-04-25 15:45 UTC, mathben commented
Dans ton message de commit, il faudrait mettre une briève description de à quoi sert croppie, ou pourquoi on l'implémente et l'utilise.

2023-04-25 15:47 UTC, guduyichengfeng commented on website_ore/data/ir_ui_view.xml
> +                                                    <i class="fa fa-pencil-square text-primary" id="submitBtn" type="submit" data-toggle="modal" data-target=".modal_pub_offre" style="padding-bottom:
J'ai enlever le type='submit', le fonctionnement est toujours correcte.

2023-04-25 15:49 UTC, guduyichengfeng commented on website_ore/static/src/js/ore_angularjs_global.js
> +                                console.debug("destroyed");
j'ai enlevé le console.debug

2023-04-25 15:50 UTC, guduyichengfeng commented on website_ore/data/ir_ui_view.xml
> +                                                <!-- TODO is it used? -->
c'est enlevé

2023-04-25 15:50 UTC, guduyichengfeng commented on website_ore/data/ir_ui_view.xml
> +                                            <!--                                            <div>-->
j'ai enlevé

2023-04-25 15:52 UTC, guduyichengfeng commented on website_ore/data/ir_ui_view.xml
> +                                                    <div class="profil profil_right profil_box btn btn-primary adapt-text-primary-color" ng-if="membre_info.estPersonnel &amp;&amp; ask_modification_pr
J'ai renommé en destroyCroppie()

2023-04-25 15:54 UTC, guduyichengfeng commented on website_ore/data/ir_ui_view.xml
> +                                                    <div class="profil profil_left profil_box btn btn-primary adapt-text-primary-color" ng-if="membre_info.estPersonnel &amp;&amp; ask_modification_pro
idem

2023-04-25 15:59 UTC, guduyichengfeng commented on website_ore/static/src/js/ore_angularjs_global.js
> +        $scope.croppie = false;
j'ai renommé à show_croppie

2023-04-25 15:59 UTC, guduyichengfeng commented on website_ore/static/src/js/ore_angularjs_global.js
> +                            console.debug("close");
J'ai supprimé

2023-04-25 16:06 UTC, guduyichengfeng commented on website_ore/static/src/js/ore_angularjs_global.js
> +                            // modal[0].setAttribute('data-backdrop', 'static'); // add the data-backdrop attribute
non

2023-04-25 16:11 UTC, guduyichengfeng commented on website_ore/static/src/js/ore_angularjs_global.js
> +                                modal[0].classList.remove('modal_shown'); // remove the modal_shown class
j'ai mis un commentaire, et j'ai pas compris la deuxième question

2023-04-25 16:13 UTC, guduyichengfeng commented on website_ore/static/src/js/ore_angularjs_global.js
> +                            $scope.show_submit_modal = false;
J'ai enlevé

2023-04-25 16:19 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +                                modal[0].classList.remove('modal_shown'); // remove the modal_shown class
la deuxième question est sur un choix technologique sur la manière d'afficher le modal, car dans participer, ça utilise une différente technique. Peut-être que ta technique est mieux. Je vais évaluer de mon coté quand tout sera terminé de ton bord :-)

2023-04-25 16:28 UTC, guduyichengfeng commented on website_ore/static/src/js/ore_angularjs_global.js
> +                                modal[0].classList.remove('modal_shown'); // remove the modal_shown class
ok, donc pour l'instant je vais laisser mon code comme ça.

2023-04-25 22:18 UTC, mathben commented on website_ore/views/assets.xml
> +
enlever ce saut de ligne

2023-04-25 22:18 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +
enlever ce saut de ligne

2023-04-25 22:27 UTC, mathben requested changes
J'ai testé la fonctionnalité.
Fait les modifications suivantes : 
1. Modifier le bouton «Crop» pour le terme français qui est «Recadrage»
2. Le bouton «Retour» devrait plutôt être nommé : «Annuler». Puis la fonctionnalité, il devrait remettre l'ancienne image comme s'il n'avait jamais uploadé l'image.
3. As-tu testé avec un navigateur web mobile?

2023-04-26 20:18 UTC, mathben approved these changes

2023-04-26 20:18 UTC, mathben commented
Merci pour cette contribution :-)

2023-04-26 20:18 UTC, mathben commented
Ça fonctionne avec le navigateur web.

2023-04-26 20:19 UTC, merged