No underline
OffrirRecevoirEchanger/erplibre-addons-ore pull request #16
Opened 2023-04-21 14:32 UTC by xSidDaKid

Bug #49: Remove the underline for the word "Membres"

2023-04-21 15:46 UTC, mathben commented
Non, ce n'est pas ce qu'il faut faire. Il faut que les URL ne surligne pas mais que ça met en surbrillance la carte.

2023-04-26 14:41 UTC, ashleyguevarra reviewed
Suggestion : Vous mettez des styles à certains endroits. Est-il possible d'utiliser des classes pour utiliser les styles ?

2023-05-17 20:39 UTC, mathben requested changes
Le code fonctionne bien, il a été mise à jour.
Il reste juste une section qui ne fonctionne pas bien, à corriger.
Exemple : http://127.0.0.1:8069/participer#!?state=init.saa.offrir.existant.form&offre_service=1&membre=1

2023-05-19 20:04 UTC, mathben approved these changes
J'observe qu'il y a des class css qui ont été mis dans des fichiers qui ne sont pas attribués au lieu d'utilisation.
Donc dans website_ore/static/src/scss/explorer/actualite.scss pour un xml dans participer.
Il faudrait faire une réorganisation des fichiers XML, pour une prochaine tâche.

Merci pour votre contribution.

2023-05-19 20:04 UTC, merged