Added the change website language feature
OffrirRecevoirEchanger/erplibre-addons-ore pull request #20
Opened 2023-05-09 22:25 UTC by xSidDaKid

The user can now change the language of website depending on his preference. The user can do so by simply his profile and going into his preferences and then choosing the desired language.

2023-05-09 22:33 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +            if (event.target.nodeName === "BUTTON") {
pourquoi as-tu besoin de vérifier le event.target.nodeName === "BUTTON" ? Quel autre combinaison est possible?

2023-05-09 22:38 UTC, xSidDaKid commented on website_ore/static/src/js/ore_angularjs_global.js
> +            if (event.target.nodeName === "BUTTON") {
Lorsqu'on n'a pas cette condition, le site va automatiquement changer de langue. Donc, si l'utilisateur choisit une langue qu'il ne comprend pas, le site va directement changer. Avec cette condition, on peut attendre que l'utilisateur click le bouton avant de changer la langue.

2023-05-16 05:11 UTC, mathben requested changes

2023-05-16 05:11 UTC, mathben commented on website_ore/controllers/main.py
> +        user_lang = request.env.user.lang or _("Français (CA)")
Le système a surement une méthode pour obtenir la langue par défaut, au lieu de hardcodé français.

2023-05-16 05:24 UTC, mathben commented on website_ore/controllers/main.py
> +        user_lang = request.env.user.lang or _("Français (CA)")
request.website.default_lang_code

2023-05-17 04:37 UTC, mathben approved these changes
Merci pour ta contribution!

2023-05-17 04:38 UTC, merged