[IMP] website_ore : Modification des champs Ma présentation
OffrirRecevoirEchanger/erplibre-addons-ore pull request #22
Opened 2023-05-16 14:57 UTC by guduyichengfeng

Pour les champs <Ma description> <Mes centres d'intérêts> <Pourquoi suis-je membre> <Langue>, Maintenant on peut tous les modifier, les données sont stocker dans le backend, il y a une validation pour l'insertion, il y a aussi une fonctionnalité de supprimer.

2023-05-16 15:44 UTC, mathben commented on ore/models/ore_membre.py
> +    langue = fields.Many2many(
Renommé pour langue_parle

2023-05-16 15:45 UTC, mathben commented on ore/models/ore_membre_langue.py
> +class ORELangue(models.Model):
Même chose ici, mettre ORELangueParle, adapté le modèle
Pour le champs name, c'est ok, pas besoin de modifier

2023-05-16 15:55 UTC, mathben requested changes

2023-05-16 15:55 UTC, mathben commented on ore/views/ore_demande_service.xml
> -                                <field name="membre_favoris_ids" widget="many2many_tags" />
pourquoi avoir enlevé ce widget?

2023-05-16 15:55 UTC, mathben commented on ore/models/ore_membre.py
> +    description = fields.Char(
c'est quoi la différence entre description et description_membre?

2023-05-16 15:55 UTC, mathben commented on ore/models/ore_membre.py
> +        help="Un petit texte qui décrit le membre.",
adapté le help en lien avec la motivation. Quel motivation?

2023-05-16 15:55 UTC, mathben commented on website_ore/controllers/main.py
> +        print("Received interets:", interets)
ne pas mettre de print. Utiliser au lieu _logger.debug()
Puis réduire les logs, utiliser un seul log au lieu d'en créer 5. Concaténer les résultats dans le même log pour faciliter le diagnostique.

2023-05-16 15:58 UTC, mathben commented
Il faut simplifier (réécrire) le message du commit

2023-05-16 15:59 UTC, mathben commented on ore/security/ir.model.access.csv
> +access_ore_membre_interet,access_ore_membre_interet,model_ore_membre_interet,base.group_user,1,1,1,1
Il semble manquer aussi base.grou_portal

2023-05-16 16:05 UTC, mathben commented on ore/security/ir.model.access.csv
> +access_ore_membre_interet,access_ore_membre_interet,model_ore_membre_interet,base.group_user,1,1,1,1
Cela cause une erreur si manquant : 
Access Denied by ACLs for operation: read, uid: 6, model: ore.membre.interet
Le problème, l'utilisateur n'est pas informé de cette erreur. Il faudrait lui afficher un message d'erreur.

2023-05-16 16:14 UTC, mathben commented
Le code fonctionne bien pour un admin. Il y a un problème, on peut faire un many2many (donc la réutilisation des entrées de langues pour d'autres utilisateurs), mais il ne peuvent pas le réutiliser. Il faut mettre une stratégie en place.

2023-05-16 16:33 UTC, mathben requested changes

2023-05-16 16:33 UTC, mathben commented on website_ore/static/src/scss/website_ore.scss
> +#add-interet {
C'est une copie de #add-langue , peut-être mettre un nom plus générique pour être réutilisé dans d'autres contextes, sinon ça complexifie la maintenance. De toute façon, on se base sur le nom de la classe qui se situe dans le XML pour retrouver la classe.
Suggestion d'utiliser le terme m2m pour many2many

2023-05-16 16:33 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                <button ng-if="ask_modification_profile" id="add-langue" ng-click="ajouterLangue()">Ajouter une langue</button>
Mettre un icone pour ajouter (un +) ou supprimer (un -)

2023-05-16 16:33 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                    <button ng-click="enregistrerLangue()" id="add-langue">Enregistrer</button>
Il manque un bouton pour annuler.
Même chose ici, au lieu de mettre enregistrer, mettre un icone (la fameuse disquette). Annuler, un X.

2023-05-16 16:35 UTC, mathben commented
Il y a l'ajout de 2 many2many, il faut pouvoir afficher à l'utilisateur les choix existants. Il n'y a pas de code existant à première vue, il faut donc le programmer.
J'ai trouvé ça
https://www.odoo.com/fr_FR/forum/aide-1/how-to-use-many2many-tags-widget-in-website-forms-v12-171012

Ça ne semble pas très bon, il faut alors programmer notre propre sélecteur.
Regarde alors autoCompleteJS
$scope.autoCompleteJS = new autoComplete(
Regarde dans le fichier participer.js

2023-05-16 17:11 UTC, guduyichengfeng commented on ore/views/ore_demande_service.xml
> -                                <field name="membre_favoris_ids" widget="many2many_tags" />
enlever par accident, j'ai remit

2023-05-16 17:12 UTC, guduyichengfeng commented on ore/models/ore_membre.py
> +    description = fields.Char(
description_membre est un boolean que vous avez créer auparavant, donc je le laisse comme ça pour l'instant

2023-05-16 17:29 UTC, guduyichengfeng commented on website_ore/controllers/main.py
> +        print("Received interets:", interets)
j'ai supprimé tous les print et console.log que j'ai utilisé, vu que la tâche est presque terminé, j'ai plus besoin de diagnostiquer

2023-05-17 21:19 UTC, mathben requested changes
Merci beau travail, il reste encore des modifications, on va réussir :-)

2023-05-17 21:19 UTC, mathben commented on website_ore/controllers/main.py
> +    self.env = env
à enlever

2023-05-17 21:19 UTC, mathben commented on website_ore/controllers/main.py
> +                "langue": a.langue_parle if a.langue_parle else "",
devrait être [] au lieu de ""

2023-05-17 21:19 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                    <q ng-cloak="">{{membre_info.description}}</q>
pas de q, c'était seulement pour un seul endroit

2023-05-17 21:19 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                <span class="nbr" ng-show="membre_info.description" ng-if="!ask_modification_profile">
Il faut changer ng-show pour ng-if et le mettre pour le bloc incluant le titre et le hr
`!_.isUndefined(membre_info.description) &amp;&amp; !_.isEmpty(membre_info.description)`

2023-05-17 21:19 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> -                                                <div class="d-flex" style="gap:1%">
est-ce mieux avec gap?

2023-05-17 21:19 UTC, mathben commented on website_ore/controllers/main.py
> +                    membre_id.langue_parle = [(4, langues_records[i].id)]
au lieu d'envoyer la liste des names, envoyer la liste des ID et utiliser [(6, 0, [IDS])]

2023-05-17 21:19 UTC, mathben commented on website_ore/controllers/main.py
> +                "langue": [rec.name for rec in membre_id.langue_parle],
Envoyer la liste des ID au client
[{"name": rec.name, "id":rec.id for rec} in membre_id.langue_parle]

2023-05-17 21:19 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                        {{langue}}
puisque la liste des ID est envoyé, langue est un objet avec clé name et id
donc
{{langue.name}}
puis ajouter un bouton supprimer ici directement et envoyer l'id (ou l'objet) dans la fonction pour effacer
<button ng-click="effacer(langue.id)"/>

2023-05-17 21:19 UTC, mathben commented on website_ore/data/ir_ui_view.xml
> +                                                    <input type="text" id="supprimeLangue" ng-model="supprimeLangue" style="margin-right: 10px;" />
Il faut changer la logique ici, mettre un bouton supprimer sur la liste et non demander à l'utilisateur de rentrer manuellement le nom de la langue à effacer.

2023-05-18 19:16 UTC, guduyichengfeng commented on website_ore/data/ir_ui_view.xml
> -                                                <div class="d-flex" style="gap:1%">
Non, gap fonctionne avec des Display: , donc selon moi je pense que c'est plus compliqué

2023-05-19 20:27 UTC, mathben requested changes
Petites corrections mineures :-)

2023-05-19 20:27 UTC, mathben commented on website_ore/controllers/main.py
> +            print("liste interet: ", [{"name": rec.name, "id": rec.id} for rec in membre_id.interet])
utiliser un _logger.debug ou juste effacer

2023-05-19 20:27 UTC, mathben commented on website_ore/controllers/main.py
> +            print("liste langue: ", [{"name": rec.name, "id": rec.id} for rec in membre_id.langue_parle])
same here, effacer

2023-05-19 20:27 UTC, mathben commented on website_ore/static/src/js/lib/autoComplete.js
> +        "class": ctx.name + "_wrapper",
revert please

2023-05-19 20:27 UTC, mathben commented on website_ore/static/src/js/ore_angularjs_global.js
> +        $scope.promptDeleteLanguage = function(langueName) {
pas besoin, on a un bouton annuler

2023-05-19 21:00 UTC, mathben approved these changes
Merci, beau travail

2023-05-20 04:54 UTC, mathben commented
J'ai fait des modifications dans une autre branche pour supporter les fonctionnalités en conflit avec 12.0_modifInfo

2023-05-20 04:54 UTC, closed without merging